version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: monthly
    versioning-strategy: increase
    open-pull-requests-limit: 10
    groups:
      allNonMajor:
        update-types:
          - 'minor'
          - 'patch'
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
