name: Setup Repo
description: Prepare repo

inputs:
  node-version:
    description: Version of Node to use
    default: 24.x

runs:
  using: composite
  steps:
    - uses: pnpm/action-setup@b906affcce14559ad1aafd4ab0e942779e9f58b1 # v4
    - name: setup Node
      uses: actions/setup-node@v6
      with:
        node-version: ${{ inputs.node-version }}
        cache: pnpm
    - run: pnpm i --frozen-lockfile
      shell: bash
