name: Setup Repo
description: Prepare repo

inputs:
  node-version:
    description: Version of Node to use
    default: 24.x

runs:
  using: composite
  steps:
    - uses: pnpm/action-setup@0977fd99725f1db4007ccb2928dbb4e90d06cc86 # v6.0.10
    - name: setup Node
      uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
      with:
        node-version: ${{ inputs.node-version }}
        cache: pnpm
    - run: pnpm i --frozen-lockfile
      shell: bash
